module.exports = {
    SET_CONNECTED_USERS: 'SET_CONNECTED_USERS',
    GET_USER: 'GET_USER',
    GET_MESSAGE: 'GET_MESSAGE',
    SET_SOCKET: 'SET_SOCKET',
    TYPING: 'TYPING',
    SET_ROOM: 'SET_ROOM',
    UPDATE_NO: 'UPDATE_NO'
}